jobs:
- job: Windows
  pool:
    vmImage: 'windows-2019'
  variables:
    buildConfiguration: 'Release'
  steps:
  - task: DotNetCoreInstaller@0
    inputs:
      version: '3.1.302'
  - script: cd $(Build.SourcesDirectory) && dotnet build
    displayName: 'Windows Full Build and Tests'
  - task: PublishTestResults@2
    inputs:
      testRunner: VSTest
      testResultsFiles: '**/*.trx'
  - task: PublishCodeCoverageResults@1
    inputs:
      summaryFileLocation: $(Build.SourcesDirectory)\artifacts\coverage.cobertura.xml
      reportDirectory: $(Build.SourcesDirectory)\artifacts
      codecoverageTool: cobertura
